# Alembic Configuration
[alembic]

# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be named with an ordering scheme
# file_template = %%(rev)03d_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to the constructor of datetime.datetime
# defaults to the value returned by datetime.datetime.now()
# timezone =

# max length of the filename (template excludes dir and .py suffix) and dialect-specific length limits are then applied.
# defaults to -1, which means no limit
# filename_template = %%(rel_filename)s-%%(py3k)s

# Whether to prepend the current date and time to the filename.
# useful so that the files can be easily sorted by the date of their creation.
# file_template = %%(created_at)s_%%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# Whether to run the migrations in a transaction or not. Defaults to True
# transaction_per_migration = True

# The SQLAlchemy URL for the database. This is overridden by the env.py file.
sqlalchemy.url = driver://user:password@localhost/dbname

# Logging configuration
[loggers]
keys = root, sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
